# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170906_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
