# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='asa', unique=True),
            preserve_default=False,
        ),
    ]
